### ISSUE TITLE
Use of Node.queue_free() results in random crashes on web export

### ISSUE THREAD

**Issue by nii236** [quaadgras/graphics.gd#107]
Minimal Reproduction Project: https://github.com/nii236/gd_mre

Exhibit A:

![Image](https://github.com/user-attachments/assets/c1ce5bd1-4480-40eb-a6ac-f96c08fd835b)

Exhibit B:

![Image](https://github.com/user-attachments/assets/6f74dbfb-520b-46cf-aeef-c233d5e2b0dd)

**Comment by Splizard** [comment]
Thanks for reporting, queue_free isn't marking the object as free on the Go side, so graphics.gd will be trying to free it as well. Will need to add a special case for this function.

**Comment by Splizard** [comment]
@nii236 I've pushed a small special case fix for queue free, to correctly invalidate the node on the Go side, I'm hoping it will resolve this issue but I haven't had the chance to check the repro yet.

**Comment by nii236** [comment]
Cheers, sadly while I *think* there's less chance of the panic happening, it still happens eventually

**Comment by nii236** [comment]
Can you have a look if the repro happens on your machine too?

**Comment by Splizard** [comment]
@nii236 planning to take a look at this soon, I am just taking care of some personal matters at this time.

**Comment by nii236** [comment]
Yeah same. Works fine on desktop, just dies on web

**Comment by nii236** [comment]
As in, the bug disappears when debug_symbols=true is enabled? 🤔

**Comment by Splizard** [comment]
> disappears when debug_symbols=true is enabled

yes...

I know it's not ideal but perhaps a work around for now would be to recycle any extension classes that you are queuing to free and hide them instead so they can be re-used if there are any previous instances available when you want to create them again?

Having these kinds of issues for the web export certainly bothers me, I think the best bet to progress on this, will be to do another full pass/review of the GDExtension `startup` interface for `js` and look to fill in any gaps, I hope this can help to uncover any underlying problems.

Another possibility may be to simplify the garbage collection implementation on web. As the current version is more oriented towards supporting native platforms.

**Comment by nii236** [comment]
> I know it's not ideal but perhaps a work around for now would be to recycle any extension classes that you are queuing to free and hide them instead so they can be re-used if there are any previous instances available when you want to create them again?

Huh, not a bad idea. I can hide it behind an interface and swap it back to queue free later, cheers.

**Comment by Splizard** [comment]
Not entirely sure what has changed here but re-running the `gd_mre` repro project on web is no longer crashing for me, I've left it running for some time and it seems to be working now.

**Comment by nii236** [comment]
Thanks for getting back to me! I spent the whole time writing up my own object pool...

**Comment by Splizard** [comment]
Maybe jumped the gun here, was testing this on a Linux machine, on Mac OS there still appears to be an issue (not sure why there is a difference between platforms on web-build stability).

**Comment by Splizard** [comment]
ok this is finally fixed! no longer able to reproduce using the new release-target export template

**Comment by nii236** [comment]
Wow, thanks for getting back to it!
